### ISSUE TITLE
BadProtoMessageException when app startup (Just armeabi-v7a)

### ISSUE THREAD

**Issue by xiazhouquan** [dappforce/subsocial-flutter#6]
Launching lib/main.dart on Redmi 6 in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:64609/NaYVQDNq1Vs=/ws
I/ial_sdk_exampl(18380): ProcessProfilingInfo new_methods=391 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter (18380): Loading Spaces from 1 to 10 ..
I/flutter (18380): Error while getting space 1 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 2 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 3 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 4 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 5 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 6 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 7 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 8 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 9 : Instance of 'BadProtoMessageException'
I/flutter (18380): Error while getting space 10 : Instance of 'BadProtoMessageException'

note: 
The bug occurred on the android armeabi-v7a platform ,bug it is ok when on the arm64-v8a

**Comment by shekohex** [comment]
I guess this happens since most of the `id`s in the app is 64-bit numbers, and since `armeabi-v7a` is a 32-bit system this error happens.

And we don't support 32-bit platforms, as there are fewer mobile devices out there is running on a 32 bit CPU.
